"""add_warranty_start

Revision ID: 34703c94b98c
Revises: 07733e58e4dc
Create Date: 2026-01-27 16:26:51.657050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34703c94b98c'
down_revision: Union[str, Sequence[str], None] = '07733e58e4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('warranty_start', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'warranty_start')
    # ### end Alembic commands ###
