"""add actor_user_id to asset_events

Revision ID: 8f6ad8b8d730
Revises: 3e780e36d06a
Create Date: 2026-01-21 23:33:15.891833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f6ad8b8d730'
down_revision: Union[str, Sequence[str], None] = '3e780e36d06a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_events', sa.Column('actor_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_asset_events_actor_user_id'), 'asset_events', ['actor_user_id'], unique=False)
    op.create_foreign_key(None, 'asset_events', 'users', ['actor_user_id'], ['id'])
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'asset_events', type_='foreignkey')
    op.drop_index(op.f('ix_asset_events_actor_user_id'), table_name='asset_events')
    op.drop_column('asset_events', 'actor_user_id')
    # ### end Alembic commands ###
