"""add_asset_requests

Revision ID: b25984cd7d6d
Revises: 3e5ee0486987
Create Date: 2026-01-28 16:16:37.535067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25984cd7d6d'
down_revision: Union[str, Sequence[str], None] = '3e5ee0486987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create new enum types
    assetrequesttype = sa.Enum('NEW_ASSET', 'EXISTING_ASSET', name='assetrequesttype')
    assetrequesttype.create(op.get_bind(), checkfirst=True)
    
    assetrequeststatus = sa.Enum('PENDING', 'APPROVED', 'DENIED', name='assetrequeststatus')
    assetrequeststatus.create(op.get_bind(), checkfirst=True)
    
    op.create_table('asset_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.Enum('NEW_ASSET', 'EXISTING_ASSET', name='assetrequesttype', create_constraint=False), nullable=False),
    sa.Column('asset_type_requested', sa.Enum('HARDWARE', 'SOFTWARE', name='assettype', create_constraint=False), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', name='assetrequeststatus', create_constraint=False), nullable=False),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_requests_asset_id'), 'asset_requests', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_requests_requester_id'), 'asset_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_asset_requests_resolved_by_id'), 'asset_requests', ['resolved_by_id'], unique=False)
    op.create_index(op.f('ix_asset_requests_status'), 'asset_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_requests_status'), table_name='asset_requests')
    op.drop_index(op.f('ix_asset_requests_resolved_by_id'), table_name='asset_requests')
    op.drop_index(op.f('ix_asset_requests_requester_id'), table_name='asset_requests')
    op.drop_index(op.f('ix_asset_requests_asset_id'), table_name='asset_requests')
    op.drop_table('asset_requests')
    # ### end Alembic commands ###
