"""add_warranty_extended_months

Revision ID: dba7d77edaa1
Revises: 34703c94b98c
Create Date: 2026-01-27 17:20:30.803311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba7d77edaa1'
down_revision: Union[str, Sequence[str], None] = '34703c94b98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('warranty_extended_months', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'warranty_extended_months')
    # ### end Alembic commands ###
